/*
 * Created on Aug 26,2015
 *
 */
package com.vsi.scc.oms.pca.order.giftCard.screens;

import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Text;

import com.yantra.yfc.rcp.IYRCComposite;
import com.yantra.yfc.rcp.IYRCPanelHolder;
import com.yantra.yfc.rcp.YRCPlatformUI;

/**
 * @author DELL
 * 
 * Generated by Sterling RCP Tools Copyright © 2005, 2006 Sterling Commerce,
 * Inc. All Rights Reserved.
 */

public class VSISendGCMailComposite extends Composite implements IYRCComposite {

	private Composite pnlRoot = null;

	private VSISendGCMailCompositeBehavior myBehavior;

	public static final String FORM_ID = "com.vsi.scc.oms.pca.screens.SendGCMailComposite";

	private Composite cmpMailDetails = null;

	private Label lblCustomerInfo = null;

	private Label lblFirstName = null;

	private Text txtFirstName = null;

	private Label lblLastName = null;

	private Text txtLastName = null;

	private Label lblEmailId = null;

	private Text txtEmailId = null;

	private Label lblGiftCardInfo = null;

	private Label lblGiftCardNo = null;

	private Text txtGiftCardNo = null;

	private Label lblPIN = null;

	private Text txtPIN = null;

	private Label labelGiftCardAmount = null;

	private Text textGiftCardAmount = null;

	private Button btnConfirm = null;

	private Button btnClose = null;

	public VSISendGCMailComposite(Composite parent, int style) {
		super(parent, style);
		initialize();
		setBindingForComponents();
		myBehavior = new VSISendGCMailCompositeBehavior(this, FORM_ID);
	}

	private void initialize() {
		this.setLayout(new FillLayout());
		createRootPanel();
		setSize(new org.eclipse.swt.graphics.Point(350, 200));
	}

	private void setBindingForComponents() {
		// TODO: set all bindings here
	}

	public String getFormId() {
		return FORM_ID;
	}

	public Composite getRootPanel() {
		return pnlRoot;
	}

	private void createRootPanel() {
		pnlRoot = new Composite(this, SWT.NONE);
		pnlRoot.setLayout(new GridLayout());
		createCmpMailDetails();
	}

	public IYRCPanelHolder getPanelHolder() {
		// TODO Complete getPanelHolder
		return null;
	}

	public String getHelpId() {
		// TODO Complete getHelpId
		return null;
	}

	/**
	 * This method initializes cmpMailDetails
	 * 
	 */
	private void createCmpMailDetails() {
		GridData gridData10 = new GridData();
		gridData10.horizontalAlignment = GridData.FILL;
		gridData10.grabExcessHorizontalSpace = true;
		gridData10.verticalAlignment = GridData.CENTER;
		GridData gridData91 = new GridData();
		gridData91.horizontalAlignment = GridData.FILL;
		gridData91.grabExcessHorizontalSpace = true;
		gridData91.verticalAlignment = GridData.CENTER;
		GridData gridData9 = new GridData();
		gridData9.horizontalAlignment = GridData.FILL;
		gridData9.verticalAlignment = GridData.FILL;
		GridData gridData8 = new GridData();
		gridData8.horizontalAlignment = GridData.FILL;
		gridData8.verticalAlignment = GridData.FILL;
		GridData gridData7 = new GridData();
		gridData7.horizontalAlignment = GridData.FILL;
		gridData7.verticalAlignment = GridData.FILL;
		GridData gridData6 = new GridData();
		gridData6.horizontalAlignment = GridData.FILL;
		gridData6.verticalAlignment = GridData.FILL;
		GridData gridData5 = new GridData();
		gridData5.horizontalAlignment = GridData.FILL;
		gridData5.verticalAlignment = GridData.FILL;
		GridData gridData4 = new GridData();
		gridData4.horizontalAlignment = GridData.FILL;
		gridData4.verticalAlignment = GridData.FILL;
		GridData gridData3 = new GridData();
		gridData3.horizontalAlignment = GridData.FILL;
		gridData3.verticalAlignment = GridData.FILL;
		GridData gridData2 = new GridData();
		gridData2.horizontalAlignment = GridData.FILL;
		gridData2.verticalAlignment = GridData.FILL;
		GridData gridData1 = new GridData();
		gridData1.horizontalAlignment = GridData.FILL;
		gridData1.verticalAlignment = GridData.FILL;
		GridData gridData = new GridData();
		gridData.horizontalAlignment = GridData.FILL;
		gridData.verticalAlignment = GridData.FILL;
		GridLayout gridLayout = new GridLayout();
		gridLayout.numColumns = 4;
		gridLayout.verticalSpacing = 10;
		gridLayout.horizontalSpacing = 25;
		
		cmpMailDetails = new Composite(getRootPanel(), SWT.NONE);
		cmpMailDetails.setLayout(gridLayout);
		cmpMailDetails.setLayoutData(gridData);
		cmpMailDetails.setLocation(100, 100);
		cmpMailDetails.setSize(300, 200);
		lblCustomerInfo = new Label(cmpMailDetails, SWT.NONE);
		lblCustomerInfo.setText("Customer Info:");
		lblCustomerInfo.setLayoutData(gridData7);
		Label filler1 = new Label(cmpMailDetails, SWT.NONE);
		Label filler = new Label(cmpMailDetails, SWT.NONE);
		Label filler2 = new Label(cmpMailDetails, SWT.NONE);
		lblFirstName = new Label(cmpMailDetails, SWT.NONE);
		lblFirstName.setText("First Name:");
		lblFirstName.setLayoutData(gridData6);
		txtFirstName = new Text(cmpMailDetails, SWT.BORDER);
		lblLastName = new Label(cmpMailDetails, SWT.NONE);
		lblLastName.setText("Last Name:");
		lblLastName.setLayoutData(gridData8);
		txtLastName = new Text(cmpMailDetails, SWT.BORDER);
		lblEmailId = new Label(cmpMailDetails, SWT.NONE);
		lblEmailId.setText("Email ID:");
		lblEmailId.setLayoutData(gridData5);
		txtEmailId = new Text(cmpMailDetails, SWT.BORDER);
		txtEmailId.setTextLimit(35);
		Label filler3 = new Label(cmpMailDetails, SWT.NONE);
		Label filler4 = new Label(cmpMailDetails, SWT.NONE);
		lblGiftCardInfo = new Label(cmpMailDetails, SWT.NONE);
		lblGiftCardInfo.setText("Gift Card Info:");
		
		lblGiftCardInfo.setLayoutData(gridData4);
		Label filler5 = new Label(cmpMailDetails, SWT.NONE);
		Label filler6 = new Label(cmpMailDetails, SWT.NONE);
		Label filler7 = new Label(cmpMailDetails, SWT.NONE);
		lblGiftCardNo = new Label(cmpMailDetails, SWT.NONE);
		lblGiftCardNo.setText("GIft Card No:");
		lblGiftCardNo.setLayoutData(gridData3);
		txtGiftCardNo = new Text(cmpMailDetails, SWT.BORDER);
		txtGiftCardNo.setTextLimit(30);
		lblPIN = new Label(cmpMailDetails, SWT.NONE);
		lblPIN.setText("PIN:");
		lblPIN.setLayoutData(gridData9);
		txtPIN = new Text(cmpMailDetails, SWT.BORDER);
		txtPIN.setTextLimit(8);

		labelGiftCardAmount = new Label(cmpMailDetails, SWT.NONE);
		labelGiftCardAmount.setText("Amount:");
		textGiftCardAmount = new Text(cmpMailDetails, SWT.BORDER);
		Label filler8 = new Label(cmpMailDetails, SWT.NONE);
		Label filler9 = new Label(cmpMailDetails, SWT.NONE);
		Label filler10 = new Label(cmpMailDetails, SWT.NONE);
		Label filler11 = new Label(cmpMailDetails, SWT.NONE);
		btnConfirm = new Button(cmpMailDetails, SWT.NONE);
		btnConfirm.setText("Confirm");
		btnConfirm.setLayoutData(gridData10);
		btnConfirm.addSelectionListener(new org.eclipse.swt.events.SelectionAdapter() {
			public void widgetSelected(org.eclipse.swt.events.SelectionEvent e) {
				String strPin = null;
				String strFirstName = null;
				String strLastName = null;
				String strMailId = null;
				String strGiftCardNo = null;
				String strGiftCardAmount = null;

				strPin = txtPIN.getText();
				strFirstName = txtFirstName.getText();
				strLastName = txtLastName.getText();
				strMailId = txtEmailId.getText();
				strGiftCardNo = txtGiftCardNo.getText();
				strGiftCardAmount = textGiftCardAmount.getText();

				if ((!YRCPlatformUI.isVoid(strFirstName.trim()))
						&& (!YRCPlatformUI.isVoid(strLastName.trim()))
						&& (!YRCPlatformUI.isVoid(strMailId.trim()))
						&& (!YRCPlatformUI.isVoid(strPin.trim()))
						&& (!YRCPlatformUI.isVoid(strGiftCardNo.trim()))
						&& (!YRCPlatformUI.isVoid(strGiftCardAmount.trim()))) {

					String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
					String intExpr = "[0-9]+";
					String numbersExp = "[[0-9]+]*[.]*[[0-9]+]*";
					if (strMailId.matches(EMAIL_REGEX) && strGiftCardNo.matches(intExpr) && strPin.matches(intExpr) && strGiftCardAmount.matches(numbersExp)) {
						String xml = String
								.format(
										"<Order EntryType=\"%s\" FirstName=\"%s\"  LastName=\"%s\" EmailID=\"%s\" GiftCardNumber=\"%s\" Pin=\"%s\" Amount=\"%s\" />","Call Center",
										strFirstName,strLastName,
										strMailId, strGiftCardNo,
										strPin,strGiftCardAmount);
						myBehavior.InsertIntoDB(xml);
					} else {
						YRCPlatformUI.showError("Error",
								"Please enter valid values!");
					}
				} else {
					YRCPlatformUI.showError("Error",
							"Please enter all the values!");
				}
			}
		});
		btnClose = new Button(cmpMailDetails, SWT.NONE);
		btnClose.setText("Close");
		btnClose.setLayoutData(gridData91);
		btnClose.addSelectionListener(new org.eclipse.swt.events.SelectionAdapter() {
			public void widgetSelected(org.eclipse.swt.events.SelectionEvent e) {
				myBehavior.doClose();
			}
		});
	}

}
