	
/*
 * Created on Dec 16,2013
 *
 */
package com.vsi.scc.oms.pca.registry;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.yantra.yfc.rcp.YRCPlatformUI;

/**
 * @author admin
 *
 * Generated by RCP Tools
 * The main plugin class to be used in the desktop.
 * Copyright © 2005, 2006 Sterling Commerce, Inc. All Rights Reserved.
 */

public class VSIPluginActivator extends AbstractUIPlugin {

	private static VSIPluginActivator plugin;
    
    public static final String ID = "com.vsi.scc.oms.pca";
	
	/**
	 * The constructor.
	 */
	public VSIPluginActivator() {
		super();
		plugin = this;
		try {
            YRCPlatformUI.registerPlugin(ID, this);			
			YRCPlatformUI.registerBundle("com.vsi.scc.oms.pca_bundle", ID);
			YRCPlatformUI.registerCommands("com.vsi.scc.oms.pca_commands", ID);
			YRCPlatformUI.registerTheme("com.vsi.scc.oms.pca_theme", ID);
			YRCPlatformUI.registerExtensions("com.vsi.scc.oms.pca_extn.yuix", ID);			
			YRCPlatformUI.registerExtensions("som.vsi.scc.oms.pca_extn.yuix", ID);	
		} catch (MissingResourceException x) {
            x.printStackTrace();
		}
	}

	/**
	 * This method is called upon plug-in activation
	 */
	public void start(BundleContext context) throws Exception {
		super.start(context);
	}

	/**
	 * This method is called when the plug-in is stopped
	 */
	public void stop(BundleContext context) throws Exception {
		super.stop(context);
	}

	/**
	 * Returns the shared instance.
	 */
	public static VSIPluginActivator getDefault() {
		return plugin;
	}

	/**
	 * Returns the plugin's resource bundle,
	 */
	public ResourceBundle getResourceBundle() {
		return null;
	}

}
