#!/bin/ksh
#
#su - shivraj.ugale -c /home/OMSAutomationScripts/Missing_Credit_Card_Expiry_Date.sh

ORACLE_HOME=/u01/app/oracle/product/11.2.0/db
LD_LIBRARY_PATH=$ORACLE_HOME/lib:$ORACLE_HOME/ctx/lib:$LD_LIBRARY_PATH
TNS_ADMIN=$ORACLE_HOME/network/admin
PATH=$ORACLE_HOME/bin:$PATH:.

#Change user, pswd and db to point to target database
USER=sterling_reader01
PWD=xpruhjJ3Px
DatabaseName=OMS_PROD

#st3rling0ms, xpruhjJ3Px, 10.3.51.167, 1881, OMSPROD_SVC

export PATH LD_LIBRARY_PATH TNS_ADMIN USER PWD DB ORACLE_HOME

LOGDIR=/home/OMSAutomationScripts

#DATASRC=/opt/web20/open/weber_order_status/production
#SHELLDIR=/export/home/vsadmin/scripts/weber_order_status/production
#SCRIPTNAME=`basename $0`

ARCDIR=$LOGDIR/arch
LOGFILE1=$LOGDIR/NoStorePickReport.txt
#LOGFILE2=$LOGDIR/CCMissingExpiryDate2.txt
TO_ADDRS="oms@vitaminshoppe.com stephen.marshall@vitaminshoppe.com Lee.Webber@vitaminshoppe.com"
#TO_ADDRS="shivraj.ugale@vitaminshoppe.com"
export LOGDIR ARCDIR PATH ORACLE_HOME USER PWD TO_ADDRS

# (YOA.CREATETS > SYSDATE - 1.25)  - This means cancellations occured in the last 30 hrs which will cover the previous day before store opens hours. Script execution time will be 8 AM every morning.
#connect $USER/$PWD@"(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.3.51.167)(PORT= 1881)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=OMSPROD_SVC)))"
#connect $USER/$PWD@"(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=lin-vsi-omspdb3)(PORT= 1881)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=OMSPROD)))"

sqlplus -silent /nolog <<END
whenever sqlerror exit 1;
whenever oserror exit 1;
set pagesize 0
set linesize 3000
set trimspool on
set feedback off
set heading off
connect $USER/$PWD@"(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.3.51.167)(PORT= 1881)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=OMSPROD_SVC)))"
spool $LOGFILE1
ALTER SESSION SET nls_date_format = 'DD-MON-YY HH12:MI:SS PM';
SELECT TRIM(TRIM(YO.EXTN_REGION)||'|'||TRIM(YO.EXTN_DISTRICT)||'|'||TRIM(YOL.SHIPNODE_KEY)||'|'||TRIM(YOH.ORDER_DATE)||'|'||TRIM(YOH.ORDER_NO)||'|'||TRIM(YOL.CUSTOMER_PO_NO)||'|'||TRIM(TRIM(YOL.ITEM_ID))||'|'||TRIM(YORS.STATUS_QUANTITY)||'|'||TRIM(YOL.LINE_TYPE)||'|'||TRIM(YS.DESCRIPTION)||'|'||TRIM(YOH.BILL_TO_ID)||'|'||TRIM(YOH.CUSTOMER_FIRST_NAME)||'|'||TRIM(YOH.CUSTOMER_LAST_NAME)||'|'||TRIM(YPI.EMAILID)||'|'||TRIM(YI.EXTN_ACT_SKU_ID)||'|'||TRIM(YOL.TAXABLE_FLAG)||'|'||TRIM(YIA.ALIAS_VALUE)||'|'||TRIM(YOL.UNIT_PRICE)||'|'||TRIM(YI.EXTN_BRAND_TITLE)||'|'||TRIM(YI.EXTN_ITEM_SIZE)||'|'||TRIM(YI.EXTN_ITEM_UOM)||'|'||TRIM(YI.EXTN_ITEM_TYPE)||'|'||TRIM(YO.EXTN_REGION_NAME)||'|'||TRIM(YO.EXTN_DISTRICT_NAME))
FROM STERLING.YFS_ORDER_HEADER YOH,STERLING.YFS_ORDER_LINE YOL,STERLING.YFS_ITEM YI,STERLING.YFS_ORDER_RELEASE_STATUS YORS,STERLING.YFS_STATUS YS,STERLING.YFS_ITEM_ALIAS YIA,STERLING.YFS_TAX_BREAKUP YTB,STERLING.YFS_PERSON_INFO YPI,STERLING.YFS_INSTRUCTION_DETAIL YID, STERLING.YFS_ORGANIZATION YO
WHERE YOH.ORDER_HEADER_KEY = YOL.ORDER_HEADER_KEY AND YI.ITEM_ID = YOL.ITEM_ID AND YOL.ORDER_LINE_KEY = YORS.ORDER_LINE_KEY AND YORS.STATUS = YS.STATUS 
AND YI.ITEM_KEY = YIA.ITEM_KEY AND YTB.LINE_KEY = YOL.ORDER_LINE_KEY AND YPI.PERSON_INFO_KEY = YOH.BILL_TO_KEY AND YOL.ORDER_LINE_KEY = YID.REFERENCE_KEY 
AND YO.ORGANIZATION_CODE = YOL.SHIPNODE_KEY AND YS.DESCRIPTION NOT IN ('Draft Order Created') AND YS.PROCESS_TYPE_KEY = 'ORDER_FULFILLMENT' AND YORS.STATUS_QUANTITY > '0' 
AND YOL.LINE_TYPE = 'PICK_IN_STORE'
AND YOH.ORDER_DATE > SYSDATE - 5
AND YOH.ORDER_NO IN (
SELECT YOH.ORDER_NO
FROM STERLING.YFS_ORDER_AUDIT YOA,STERLING.YFS_ORDER_HEADER YOH
WHERE YOA.ORDER_HEADER_KEY = YOH.ORDER_HEADER_KEY AND YOH.DOCUMENT_TYPE = '0001' AND YOH.DRAFT_ORDER_FLAG = 'N' 
AND YOA.CREATETS > SYSDATE - 1.25 
AND YOA.REASON_CODE = 'NO_STORE_PICK'
)
ORDER BY YOH.ORDER_DATE DESC;
spool off
exit 0
END

order_msg=$(cat $LOGFILE1)

orderCount=$(sqlplus -silent /nolog <<END
whenever sqlerror exit 1;
whenever oserror exit 1;
set pagesize 0
set feedback off
set heading off
connect $USER/$PWD@"(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.3.51.167)(PORT= 1881)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=OMSPROD_SVC)))"
SELECT COUNT(DISTINCT(YOH.ORDER_NO)) AS C
FROM STERLING.YFS_ORDER_HEADER YOH,STERLING.YFS_ORDER_LINE YOL,STERLING.YFS_ITEM YI,STERLING.YFS_ORDER_RELEASE_STATUS YORS,STERLING.YFS_STATUS YS,STERLING.YFS_ITEM_ALIAS YIA,STERLING.YFS_TAX_BREAKUP YTB,STERLING.YFS_PERSON_INFO YPI,STERLING.YFS_INSTRUCTION_DETAIL YID, STERLING.YFS_ORGANIZATION YO
WHERE YOH.ORDER_HEADER_KEY = YOL.ORDER_HEADER_KEY AND YI.ITEM_ID = YOL.ITEM_ID AND YOL.ORDER_LINE_KEY = YORS.ORDER_LINE_KEY AND YORS.STATUS = YS.STATUS 
AND YI.ITEM_KEY = YIA.ITEM_KEY AND YTB.LINE_KEY = YOL.ORDER_LINE_KEY AND YPI.PERSON_INFO_KEY = YOH.BILL_TO_KEY AND YOL.ORDER_LINE_KEY = YID.REFERENCE_KEY 
AND YO.ORGANIZATION_CODE = YOL.SHIPNODE_KEY AND YS.DESCRIPTION NOT IN ('Draft Order Created') AND YS.PROCESS_TYPE_KEY = 'ORDER_FULFILLMENT' AND YORS.STATUS_QUANTITY > '0' 
AND YOL.LINE_TYPE = 'PICK_IN_STORE'
AND YOH.ORDER_DATE > SYSDATE - 5
AND YOH.ORDER_NO IN (
SELECT YOH.ORDER_NO
FROM STERLING.YFS_ORDER_AUDIT YOA,STERLING.YFS_ORDER_HEADER YOH
WHERE YOA.ORDER_HEADER_KEY = YOH.ORDER_HEADER_KEY AND YOH.DOCUMENT_TYPE = '0001' AND YOH.DRAFT_ORDER_FLAG = 'N' 
AND YOA.CREATETS > SYSDATE - 1.25 
AND YOA.REASON_CODE = 'NO_STORE_PICK');
exit 0
END
)

if [ $? -ne 0 ]
then
echo "****Error in the process****"
DT=`date +%h_%d_%Y`
TM=`date +%H:%M:%S`
echo "${DT}_${TM}"|mailx -s "Error running NO STORE PICK report" $TO_ADDRS
elif [ $orderCount -eq 0 ]
then
echo -e "This mornings query displayed no orders cancelled due to NO STORE PICK." | mailx -r "oms_auto_notification@vitaminshoppe.com" -s "No orders cancelled due to NO STORE PICK" $TO_ADDRS
elif [ $orderCount -gt 0 ]
then
REPORTDATE=`date +%Y_%m_%d`
echo -e "Cancelled ORDERS due to NO STORE PICK.\n\nPlease create a report using the attached file."|mailx -r "oms_auto_notification@vitaminshoppe.com" -s "NO STORE PICK REPORT $REPORTDATE. Count:$orderCount" -a $LOGDIR/NoStorePickReport.txt $TO_ADDRS
fi